# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8043c4d1647eb6b481fadba3a45dde3927115bce431fc07283e23213c2d7ffa8f8d4b3c914ca0f9959040c347056467a93316d739dc3cd850bb5367ad9cbcfc7

test:
  secret_key_base: a9dc63244e7bf7bed3d5b0abb5408049072057cc402758c549333c21bba5e4fb907540416741209e2f212279645eae61d70336e8c9f1af230c996e759a85f6ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
